version: 2.1

jobs:
  plan-apply:
    working_directory: ~/host_a_static_website_in_AWS
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform - fmt and Init 
          command: |
            terraform fmt -recursive .
            terraform init -input=false 
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform - Apply
          command: |
            terraform apply -auto-approve 
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
      docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Terraform - Destroy
            command: |
              terraform destroy -auto-approve 

workflows:
  terraform_plan_apply_destroy_sftp:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
      - apply:
          requires:
            - hold-apply
      - hold-destroy:
          type: approval
          requires:
            - apply
      - destroy:
          requires:
            - hold-destroy
