version: 2.1

jobs:

  initialization:
    working_directory: ~/host_a_static_website_in_AWS
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - run:
          name: terraform init 
          command: |
            terraform init  
      - persist_to_workspace:
          root: .
          paths:
            - .
  validate:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      - image: cimg/aws:2024.03
    parallelism : 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform validate
          command: |
            terraform validate
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      - image: cimg/aws:2024.03
    parallelism : 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            apk add -U --no-cache jq
            terraform apply -auto-approve 
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
      - image: cimg/aws:2024.03
    parallelism : 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform destroy -auto-approve 
      - persist_to_workspace:
          root: .
          paths:
            - .
 
workflows:
  plan_approve_apply:
    jobs:
      - initialization
      - validate:
          requires:
            - initialization
      - apply:
          requires:
            - validate
      - hold-destroy:
          type: approval
          requires:
            - apply
      - destroy:
          requires:
            - hold-destroy
    