name: Deploy Static Website

on:
  push:
    branches:
      - main     

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  

    - name: Install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
          version: 2                         
          verbose: false                     
          arch: amd64

    - name: Terraform Init
      run: terraform init
  
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2

    - name: Output website URL
      run: echo "Website URL is $(terraform output INFO)"
